/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Hamburger(props) {
  const { nodes, materials } = useGLTF('./hamburger.glb')
  return (
    <group {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="bottomBun"
          geometry={nodes.bottomBun.geometry}
          material={materials.BunMaterial}
        />
        <mesh
          name="meat"
          geometry={nodes.meat.geometry}
          material={materials.SteakMaterial}
          position={[0, 2.8173, 0]}
        />
        <mesh
          name="cheese"
          geometry={nodes.cheese.geometry}
          material={materials.CheeseMaterial}
          position={[0, 3.04, 0]}
        />
        <mesh
          name="topBun"
          geometry={nodes.topBun.geometry}
          material={materials.BunMaterial}
          position={[0, 1.7711, 0]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/hamburger.glb')
